---
name: Release

on:
  workflow_dispatch:
    inputs:
      scope:
        description: Release scope
        required: true
        default: minor
        type: choice
        options:
          - major
          - minor
          - patch

concurrency:
  group: publish-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release:
    uses: moderneinc/gh-automation/.github/workflows/publish-maven-artifact.yml@main
    with:
      release_scope: ${{ github.event.inputs.scope }}
    secrets:
      google_cloud_service_account_key: ${{ secrets.ARTIFACT_REGISTRY_KEY }}
      caller_github_token: ${{ secrets.GITHUB_TOKEN }}
      moderne_artifactory_username: ${{ secrets.moderne_artifactory_username }}
      moderne_artifactory_password: ${{ secrets.moderne_artifactory_password }}
